import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { GlobalStateProvider } from "@/context/GlobalStateProvider";
import { Providers } from "./providers";
import NavbarComponent from "@/components/NavbarComponent";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <main>
          <GlobalStateProvider>
            <Providers>
              <NavbarComponent />
              <main className="pt-16 flex flex-col justify-center items-center w-full flex-wrap px-4 lg:px-8">
                {children}
              </main>
            </Providers>
          </GlobalStateProvider>
        </main>
      </body>
    </html>
  );
}
